monitor.bluez.rules = [
  {
    matches = [
      {
        device.name = "bluez_card.84_17_15_05_D3_28"
      }
    ]
    actions = {
      update-props = {
        bluez5.auto-connect = [ a2dp_sink ]
      }
    }
  }
]
